### ISSUE TITLE
submmit stopped

### ISSUE THREAD

**Issue by cornorghost** [spancer/flink-iceberg-demo#2]
i try flink-kafka-test，but stock here like this, no submmitted job found on web ui
![image](https://user-images.githubusercontent.com/33841855/219951769-09880a3e-9e79-4a46-a2af-da36db85bdac.png)

**Comment by spancer** [comment]
you have to provide more logs.

**Comment by spancer** [comment]
logs show that you've done well. The job has been successfully submited. Just check your yarn logs or running job on yarn web ui.
